language: php

php:
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - vendor/bin/phpunit 
  #- docker build -t mikellf/despliegue .

deploy:
  #provider: heroku
  #api_key: 
  #app: daw-conversor-2020

  #provider: script
  #script: docker push mikellf/despliegue
  #on:
    #branch: master
