language: php

php:
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - vendor/bin/phpunit 
  - docker build -t mikellf/daw-conversor-2020 .

deploy:
  provider: heroku
  api_key: d56ab021-0e25-49c1-a661-891596fbdbc9
  app: daw-conversor-2020-miguel

  provider: script
  script: docker push mikellf/daw-conversor-2020
  on:
    branch: master
